version: "3"

services:

  web:
    build: .
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./log:/var/log/nginx/
      - ./my_nginx.conf:/etc/nginx/conf.d/default.conf
    command: ["nginx", "-g", "daemon off;"]
    networks:
      - mail-app

networks:
  mail-app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.243.0/24
